name: Deploy Theme to ColorfulBox

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - run: echo "軽量な処理"
    
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    
    - name: Sync Theme Directory
      run: |
        rsync -avz --delete \
        --exclude='.git/' \
        --exclude='.github/workflows/deploy.yml' \
        ./ \
        ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.THEME_PATH }}